import os
import json
import uuid
import glob

try:
    from google import genai
    from google.genai import types
    HAS_GENAI = True
except ImportError:
    HAS_GENAI = False

def main():
    print("=== Phase 5: Content & SEO Generator ===")
    
    # Setup paths
    script_dir = os.path.dirname(os.path.abspath(__file__))
    assets_dir = os.path.join(script_dir, "final_pdp_assets")
    src_dir = os.path.abspath(os.path.join(script_dir, "..", "src"))
    products_json_path = os.path.join(src_dir, "products.json")
    
    if not os.path.exists(assets_dir):
        print(f"Error: Assets directory not found at {assets_dir}")
        return
        
    if not os.path.exists(src_dir):
        print(f"Creating src directory at {src_dir}")
        os.makedirs(src_dir, exist_ok=True)
        
    # Load .env file if it exists
    env_path = os.path.join(script_dir, "..", ".env")
    if os.path.exists(env_path):
        with open(env_path, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, val = line.split("=", 1)
                    os.environ[key.strip()] = val.strip().strip("'").strip('"')
    
    brief = input("Enter the design brief for the product (e.g., 'A vintage Oklahoma City Thunder inspired shirt'): ").strip()
    if not brief:
        print("No brief provided. Using a default brief.")
        brief = "A vintage Oklahoma City Thunder inspired shirt"
        
    print(f"\n[API] Generating SEO content for: '{brief}'...")
    
    # Default fallback data
    product_data = {
        "id": str(uuid.uuid4()),
        "title": "Generated T-Shirt",
        "description": "An awesome t-shirt generated by the pipeline.",
        "meta_tags": ["t-shirt", "apparel"],
        "images": []
    }
    
    if HAS_GENAI and os.environ.get("GEMINI_API_KEY"):
        client = genai.Client()
        try:
            print("Calling Gemini API...")
            prompt = f"""You are an SEO expert. Given this product brief, generate a JSON object with:
- "title": An SEO-optimized product title.
- "description": An SEO-optimized product description.
- "meta_tags": A list of relevant SEO meta tags (strings).

Product Brief:
{brief}
"""
            
            response = client.models.generate_content(
                model='gemini-2.5-flash',
                contents=prompt,
                config=types.GenerateContentConfig(
                    response_mime_type="application/json",
                ),
            )
            
            result = json.loads(response.text)
            product_data["title"] = result.get("title", product_data["title"])
            product_data["description"] = result.get("description", product_data["description"])
            product_data["meta_tags"] = result.get("meta_tags", product_data["meta_tags"])
            print("Successfully generated SEO content.")
            print(f"Title: {product_data['title']}")
        except Exception as e:
            print(f"Error during Gemini API generation: {e}")
            print("Falling back to default SEO content.")
    else:
        print("Gemini API key or google-genai not found. Using default SEO content.")
        print("To use real generation, ensure 'google-genai' is installed and GEMINI_API_KEY is set.")
        
    # Grab image paths
    print("\nScanning final_pdp_assets for images...")
    image_files = glob.glob(os.path.join(assets_dir, "*.png"))
    
    project_root = os.path.abspath(os.path.join(script_dir, ".."))
    
    image_paths = []
    for img in image_files:
        # Save relative paths from the project root so the frontend can easily reference them
        rel_path = os.path.relpath(img, project_root)
        image_paths.append(rel_path)
        print(f"Found image: {rel_path}")
        
    product_data["images"] = image_paths
    
    # Load existing products or create new list
    products = []
    if os.path.exists(products_json_path):
        try:
            with open(products_json_path, "r") as f:
                content = f.read().strip()
                if content:
                    products = json.loads(content)
        except Exception as e:
            print(f"Warning: Could not read existing {products_json_path}. Starting fresh. Error: {e}")
            
    # Prepend new product so it appears first
    products.insert(0, product_data)
    
    # Write back to products.json
    try:
        with open(products_json_path, "w") as f:
            json.dump(products, f, indent=4)
        print(f"\n[SUCCESS] Saved product data to {products_json_path}")
    except Exception as e:
        print(f"Error saving to {products_json_path}: {e}")

if __name__ == "__main__":
    main()
